interface ITankMazeLevel {
	road: boolean[][][];
	stones: boolean[][];
	gas: boolean[][];
}

const levels: { [key: number]: ITankMazeLevel } = {
  0: {
    road: [
      [
        [false, false, false, false],
        [false, true, true, true],
        [true, true, false, false],
        [true, true, false, true],
        [true, true, false, false],
        [true, true, false, true],
        [true, false, false, true],
      ],
      [
        [false, true, false, true],
        [true, true, true, true],
        [true, true, false, false],
        [true, true, true, false],
        [true, true, false, false],
        [true, false, true, true],
        [false, false, true, true],
      ],
      [
        [false, false, true, true],
        [false, false, true, true],
        [false, true, false, true],
        [true, true, false, true],
        [true, true, false, true],
        [true, true, true, false],
        [true, false, true, true],
      ],
      [
        [false, true, true, false],
        [true, true, true, true],
        [true, true, true, true],
        [true, true, true, true],
        [true, false, true, true],
        [false, true, false, true],
        [true, false, true, false],
      ],
      [
        [false, true, false, true],
        [true, true, true, true],
        [true, true, true, true],
        [true, false, true, true],
        [false, false, true, true],
        [false, true, true, false],
        [true, false, false, true],
      ],
      [
        [false, true, true, false],
        [true, true, true, false],
        [true, true, true, true],
        [true, true, true, true],
        [true, true, true, true],
        [true, true, false, true],
        [true, false, true, false],
      ],
      [
        [false, true, false, true],
        [true, true, false, false],
        [true, false, true, false],
        [false, true, true, false],
        [true, true, true, false],
        [true, true, true, true],
        [true, false, false, true],
      ],
      [
        [false, true, true, true],
        [true, true, false, false],
        [true, true, false, true],
        [true, true, false, true],
        [true, false, false, true],
        [false, true, true, false],
        [true, false, true, true],
      ],
      [
        [false, true, true, false],
        [true, true, false, false],
        [true, true, true, false],
        [true, false, true, true],
        [false, true, true, false],
        [true, true, false, false],
        [true, false, true, false],
      ],
    ],
    stones: [
      [false, false, false, false, false, true, false],
      [false, false, false, true, false, false, false],
      [false, true, false, false, false, false, true],
      [false, false, false, false, true, false, false],
      [false, true, false, true, false, false, false],
      [false, false, false, false, false, false, false],
      [false, true, false, true, false, true, false],
      [true, false, true, false, false, false, false],
      [false, true, false, false, true, true, true],
    ],
    gas: [
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, false],
      [false, false, false, false, false, false, true],
      [false, false, false, false, false, false, false],
    ],
  },
};
